
package org.papamitra.android.dbhelper

trait MappedField[FieldType <: Any, OwnerType <: Mapper[OwnerType]] {

  def dbColumnType

  def dbColumnTypeStr:String

  def isAutoGenerated:Boolean = fieldOwner.primaryKeyField == this

  private var data: Option[FieldType] = None

  def is: Option[FieldType] = data

  private var _name: Option[String] = None

  def name:String = _name.getOrElse("")

  def fieldOwner: OwnerType

  def set(f: FieldType): Option[FieldType] = { data = Some(f); data }

  def setName(name: String) = {
    _name = Some(name)
    _name
  }

  def apply(v: FieldType): OwnerType = { // issue 154
    this.set(v)
    fieldOwner
  }
}
